version: "3.8"
services:
  frontend-app:
    image: stephnorman/frontend-image:latest
    build: ./frontend
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  backend-app:
    image: stephnorman/backend-image:latest
    build: ./backend
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx.conf
      target: /etc/nginx/nginx.conf
